<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BF400255" ignored="0" name="Test01_test01" tests="3" failures="1" timestamp="22 六月 2020 09:49:21 GMT" time="0.046" errors="0">
  <testcase name="test01" time="0.01" classname="com.course.Test01">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.course.Test01.test01(Test01.java:11)
	at com.course.Test03.main(Test03.java:22)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test01 -->
  <testcase name="test02" time="0.0" classname="com.course.Test01"/>
  <testcase name="test03" time="0.0" classname="com.course.Test01"/>
</testsuite> <!-- Test01_test01 -->
